### PR TITLE
LEAKS: Fix leaks during console tab completion

### PR DESCRIPTION
**Pull request by JosephPecoraro**
Numerous leaks when doing tab completion in the console.

Namely every time either escape_regex or str_repeat is called, if they allocated they will leak.

To reproduce:

1. Open console
2. Type "src" <tab>

### CODE REVIEW

**Comment by jite** [comment]
Good finds, there are a lot of these "stupid" leaks everywhere. I'd recommend that when touching code that uses va(), rewrite it to get rid of the va() usage instead. I don't like assignments within func/macro calls. Would you mind rewriting it a bit to get rid of the va() usage completely? Thanks

**Comment by jite** [comment]
Oh and btw, hello from sunny honeymoon in Skiathos, Greece :)

**Comment by JosephPecoraro** [comment]
Hello ;)

Good suggestions. I made a helper function to print the mark and pad. It makes the `str_repeat` allocation tracking simpler, and simplifies `PaddedPrintValue` by avoiding crazy long lines.

**Comment by meag** [comment]
Included: https://github.com/ezQuake/ezquake-source/commit/a3e790ba8a3bf5a2f7c47814d41f18602b2b48a6 & https://github.com/ezQuake/ezquake-source/commit/2c07a85540220534a998c33d344a4d271a0c0eab

**Pull request closed without merging**
