### PR TITLE
Minor .dem playback fixes & fix for blank autoscreenshot.

### PR DESCRIPTION
**Pull request by meag**

### CODE REVIEW

**Comment by jite** [comment]
Thanks for the fixes, great work! :+1:  On a git side of things it would be better if you could rebase your changes to master first, that way we would get rid of the "merge commit" and get your fixes applied on top of current master head :)

**Comment by jite** [comment]
I'll merge this in, just a friendly note to next time ;)

**Comment by meag** [comment]
Apologies - spot the git newbie.  Just reading up on it now - "You could do a merge, but that causes the branch to contain weird merge commits that make reviewing the pull request much more difficult. Instead, you can do a rebase." - doh.  Will sort that for the next time, apologies again.

**Comment by jite** [comment]
No worries, you usually don't know about things before you know about'em :) Think about a rebase as cutting your changes out and reapplying them on top (not necessarily but the most common option).

Another good to know thing: always do `git pull --rebase` if you have made local commits not on upstream repo yet. If your local repo is behind then you will get one of these ugly merges first and then your commits on top. If you do it with the --rebase then your changes will be reverted, upstream repo will be pulled and then your changes will be applied on top of the repo.

**Pull request merged**
