### PR TITLE
Limitation of the cl_rollangle from 0 to 10 for ruleset thunderdome

### PR DESCRIPTION
**Pull request by VVD**
I think this limitation must be applied for qcon and smackdown rulesets too.

Please, commit it and create release 3.2.3 before Thunderdome 15 starts at middle of February.

Patch in attach:
[ezquake-source.rollangle.diff.txt](https://github.com/ezQuake/ezquake-source/files/5826507/ezquake-source.rollangle.diff.txt)

### CODE REVIEW

**Comment by meag** [comment]
Can you rebase, I think you've merged instead?

just to note: smackdown & qcon both have unlimited `cl_rollangle` but block `cl_rollalpha`, so if you wanted to abuse it you'd have to be standing still or be very good at playing while being seasick.  (I still think it should be limited)

**Comment by meag** [comment]
Actually I don't know what you've done, you're trying to pull 3.2->3.2.2 into 3.6?  there's no commit but just a diff file?

**Comment by VVD** [comment]
> Can you rebase, I think you've merged instead?

I do not know what you're talking.…

> Actually I don't know what you've done, you're trying to pull 3.2->3.2.2 into 3.6? there's no commit but just a diff file?

Yes, it's diff file.

> just to note: smackdown & qcon both have unlimited cl_rollangle but block cl_rollalpha. so if you wanted to abuse it you'd have to be standing still or be very good at playing while being seasick

I know. But somebody still can use same "cheating abuse" with high values of cl_rollangle as with cl_rollalpha 20, if he can do it with cl_rollalpha 0 (IMHO, both are impossible).

**Comment by VVD** [comment]
Tried to make pull request from a file without fork the whole repo…

**Comment by meag** [comment]
image

Looks like even 10 is quite 'generous', 5 or even 3 would be better?

**Comment by VVD** [comment]
I'm using in game 5. More than 5 is worse for me. 10 is a lot - agree.
We can ask "high qw council" for this limit. :-D
Any number from 5 to 10 is ok for me.

**Comment by blaps** [comment]
I vote 5

**Comment by VVD** [comment]
You can create 5 then.

**Comment by VVD** [comment]
I need version with cl_rollangle limitation for start TD15.

**Comment by VVD** [comment]
Thanks.

**Pull request closed without merging**
